# Generated by Django 5.2.15 on 2026-07-06 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodel',
            name='nit',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="NIT inválido. Formato: 6-10 dígitos, opcionalmente '-' + dígito verificador. Ej: 900123456-7", regex='^\\d{6,10}(-\\d)?$')]),
        ),
        migrations.AlterField(
            model_name='empresamodel',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Teléfono inválido. Formato: +57 601 234 5678', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')]),
        ),
        migrations.AddConstraint(
            model_name='empresamodel',
            constraint=models.CheckConstraint(condition=models.Q(('nit__regex', '^\\d{6,10}(-\\d)?$')), name='chk_empresa_nit_format', violation_error_message="NIT inválido. Formato: 6-10 dígitos, opcionalmente '-' + dígito verificador."),
        ),
        migrations.AddConstraint(
            model_name='empresamodel',
            constraint=models.CheckConstraint(condition=models.Q(('telefono__regex', '^\\+?[\\d\\s\\-\\(\\)]{7,20}$')), name='chk_empresa_telefono_format', violation_error_message='Teléfono inválido.'),
        ),
    ]
