# Generated by Django 5.2.15 on 2026-07-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariomodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventariomodel',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='products.productomodel'),
        ),
    ]
